// src/features/searchSlice.js

import { createSlice } from '@reduxjs/toolkit'; // Import createSlice function from Redux Toolkit

// Define the searchSlice using createSlice
const searchSlice = createSlice({
  name: 'search', // Slice name
  initialState: {
    query: '', // Initial state for search query
    results: [], // Initial state for search results
    loading: false, // Initial state for loading status
  },
  reducers: {
    // Reducer function to set the search query
    setQuery: (state, action) => {
      state.query = action.payload; // Update query state with payload
    },
    // Reducer function to set the search results
    setResults: (state, action) => {
      state.results = action.payload; // Update results state with payload
    },
    // Reducer function to set the loading status
    setLoading: (state, action) => {
      state.loading = action.payload; // Update loading state with payload
    },
  },
});

// Export actions generated by createSlice
export const { setQuery, setResults, setLoading } = searchSlice.actions;

// Export reducer function generated by createSlice
export default searchSlice.reducer;
