
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import React from 'react';
import { Provider } from 'react-redux';
import { store } from 'redux';
import ServerLayout from './server-layout';
import ClientProvider from './ClientProvider';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ServerLayout>
      <ClientProvider>
        {children}
      </ClientProvider>
    </ServerLayout>
  );
}